### ISSUE TITLE
import in react/next

### ISSUE THREAD

**Issue by Pfurr** [chr-ge/react-column-select#18]
Hi, good job! Can you explain how to import into React Js/Next Js?

There's an import like: 

```import ColumnSelectExample from "@react-column-select";```

**Comment by chr-ge** [comment]
I'm glad you like it but it's not ready to be used in a project yet.
If you wanna play around with what I've done so far, you can import it with:
`import ColumnSelect from 'react-column-select'` and give it an array of options.
You can see the list of props on the README.md file.

**Comment by Pfurr** [comment]
ah ok, thank you! ::)) i'll see if I can play with it a little bit

**Comment by chr-ge** [comment]
I will be releasing v1 very soon :)
